name: C++ Build and Package Pipeline

on:
  push:
    branches:
      - branchAutomake
  pull_request:
    branches:
      - branchAutomake

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Autotools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool build-essential

      - name: Generate configuration files
        run: |
          aclocal
          autoconf
          autoheader
          automake --add-missing

      - name: Configure and build
        run: |
          ./configure
          make
          ./program

      - name: Create distribution tarball
        run: |
          make dist
          ls -l *.tar.gz # Verify tarball creation

      - name: Upload distribution tarball
        uses: actions/upload-artifact@v3
        with:
          name: program-tarball
          path: "*.tar.gz"

