name: C++ Build and Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool build-essential

      - name: Generate configuration files
        run: |
          aclocal
          autoconf
          autoheader
          automake --add-missing

      - name: Configure and build
        run: |
          ./configure
          make

      - name: Run unit tests
        run: |
          make check

      - name: Verify the test output
        run: |
          ./test_arctangent #Ensure the test runs successfully

      - name: Run the program
        run: |
          ./program

