name: C++ Build and Test Pipeline

on:
  push:
    branches:
      - branchAutoTest
  pull_request:
    branches:
      - branchAutoTest

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools and debhelper
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool build-essential

      - name: Generate configuration files
        run: |
          aclocal
          autoconf
          autoheader
          automake --add-missing

      - name: Configure and build
        run: |
          ./configure
          make

      - name: Run unit tests
        run: |
          make check

      - name: Verify the test output
        run: |
          ./test_arctangent # Ensure the unit test runs successfully

      - name: Run the program
        run: |
          ./program

