name: AMD64&ARM64 Docker image build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: QEMU install
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build ls
        run: docker buildx ls

      - name: Log in to dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build AMD64 Dockerfile image
        run: docker build --platform=linux/amd64 -t tr23malyarchuk/pa-tr23malyarchuk:amd64 --push .

      - name: Build ARM64 Dockerfile image
        run: docker build --platform=linux/arm64 -t tr23malyarchuk/pa-tr23malyarchuk:arm64 --push .

      - name: Create manifest
        run: docker manifest create tr23malyarchuk/pa-tr23malyarchuk --amend tr23malyarchuk/pa-tr23malyarchuk:amd64 --amend tr23malyarchuk/pa-tr23malyarchuk:arm64

      - name: Push manifest to docker hub
        run: docker manifest push tr23malyarchuk/pa-tr23malyarchuk

