name: C++ Build and Debian Package Pipeline

on:
  push:
    branches:
      - branchAutoPackage
  pull_request:
    branches:
      - branchAutoPackage

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools and debhelper
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake devscripts debhelper build-essential

      - name: Generate configuration files
        run: |
          aclocal
          autoconf
          autoheader
          automake --add-missing

      - name: Configure and build
        run: |
          ./configure
          make
          ./program

      - name: Build Debian package
        run: |
          dpkg-buildpackage -us -uc

      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: "./*.deb"

